# Generated by Django 4.2.2 on 2023-06-14 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "loan_amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Approved", "APPROVED"),
                            ("Reject", "REJECTED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adress",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="address.address",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
